# Generated by Django 3.2.25 on 2025-03-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_forbiddenword'),
    ]

    operations = [
        migrations.AddField(
            model_name='encouragement',
            name='style',
            field=models.CharField(choices=[('keigo', '敬語'), ('tamego', 'タメ語')], default='keigo', max_length=10),
        ),
    ]
