# Generated by Django 3.2.25 on 2025-03-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_encouragement_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('location', models.CharField(max_length=200, verbose_name='場所')),
                ('person', models.CharField(max_length=100, verbose_name='相手(誰に)')),
                ('description', models.TextField(verbose_name='出来事の詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
        ),
    ]
