# Generated by Django 3.2.25 on 2025-03-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_incident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'verbose_name': '出来事', 'verbose_name_plural': '出来事一覧'},
        ),
    ]
